blank_issues_enabled: true
contact_links:
  - name: ğŸ™‹ğŸ¾ Question
    url: https://github.com/riipandi/moonlight/discussions/new/choose
    about: Use this link to submit your question to GitHub Discussions.
